apiVersion: v2
name: odk-central-pyxform
description: A Helm chart for odk-central-pyxform.
type: application
version: v2025.2.2
dependencies:
- name: common
  repository: https://openg2p.github.io/openg2p-helm
  version: 2.30.0
keywords:
  - odk
  - odk-central
  - odk-central-pyxform
