apiVersion: v2
name: mock-identity-system
description: A Helm chart for MOSIP Mock Identity System module
type: application
version: 0.9.5
appVersion: 0.9.3
dependencies:
- name: common
  repository: https://openg2p.github.io/openg2p-helm
  version: 2.30.0
home: https://mosip.io
keywords:
  - mosip
  - esignet
  - mock-identity-system
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "Mock Identity System"
