apiVersion: v1
kind: ConfigMap
metadata:
  name: global
data:
  installation-name: openg2p
  installation-domain: ${SANDBOX_HOSTNAME}
  mosip-version: develop
  mosip-api-host: ${SANDBOX_HOSTNAME}
  mosip-api-internal-host: ${SANDBOX_HOSTNAME}
  mosip-prereg-host: prereg.${SANDBOX_HOSTNAME}
  mosip-activemq-host: activemq.${SANDBOX_HOSTNAME}
  mosip-kibana-host: kibana.${SANDBOX_HOSTNAME}
  mosip-admin-host: admin.${SANDBOX_HOSTNAME}
  mosip-regclient-host: regclient.${SANDBOX_HOSTNAME}
  mosip-minio-host: minio.${SANDBOX_HOSTNAME}
  mosip-kafka-host: kafka.${SANDBOX_HOSTNAME}
  mosip-iam-external-host: keycloak.${SANDBOX_HOSTNAME}
  mosip-postgres-host: ${SANDBOX_HOSTNAME}
  mosip-pmp-host: pmp.${SANDBOX_HOSTNAME}
  mosip-resident-host: resident.${SANDBOX_HOSTNAME}
  mosip-compliance-host: compliance.${SANDBOX_HOSTNAME}
  mosip-esignet-host: esignet.${SANDBOX_HOSTNAME}
  mosip-smtp-host: smtp.${SANDBOX_HOSTNAME}
  is_glowroot_env: absent
