apiVersion: v2
name: odk-central-frontend
description: A Helm chart for odk-central-frontend.
type: application
version: "v2024.1.0"
appVersion: ""
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
keywords:
  - odk
  - odk-central
  - odk-central-frontend
