annotations:
  category: Infrastructure
apiVersion: v2
appVersion: latest
dependencies:
- name: common
  condition: enabled
  version: 1.11.1
description: LocalStack - a fully functional local AWS cloud stack
icon: https://localstack.cloud/images/localstack.png
keywords:
- aws
- localstack
maintainers:
- email: info@localstack.cloud
  name: LocalStack Team and Community
name: localstack
sources:
- https://localstack.cloud/
- https://github.com/localstack/localstack
type: application
version: 0.4.3
