apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Password
  database-password: {{ .Values.postgresql.auth.password | quote }}
  
  # Strapi Security Keys
  app-keys: {{ .Values.strapi.appKeys | quote }}
  api-token-salt: {{ .Values.strapi.apiTokenSalt | quote }}
  admin-jwt-secret: {{ .Values.strapi.adminJwtSecret | quote }}
  transfer-token-salt: {{ .Values.strapi.transferTokenSalt | quote }}
  jwt-secret: {{ .Values.strapi.jwtSecret | quote }}
  
  # Admin Password
  admin-password: {{ .Values.strapi.admin.password | quote }}