apiVersion: v2
name: esignet
description: A Helm chart for MOSIP eSignet module
type: application
version: 1.4.3
appVersion: 1.4.1
dependencies:
- name: common
  repository: https://openg2p.github.io/openg2p-helm
  version: 2.30.0
home: https://mosip.io
keywords:
  - mosip
  - esignet
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "eSignet"
