apiVersion: v2
name: keycloak-init
description: A Helm chart for OpenG2P to initialize Keycloak-clients
type: application
version: 0.0.0-develop
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P Keycloak Init"


