apiVersion: v2
name: mail
description: A Helm chart for mail/smtp server.
type: application
version: "1.2.1"
appVersion: ""
dependencies:
- name: common
  repository: https://openg2p.github.io/openg2p-helm
  version: 2.30.0
keywords:
  - mail
  - smtp
