global:
  # domain name of installation
  # mailname: "example.com"
  mailname: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 25

image:
  registry: docker.io
  repository: ixdotai/smtp
  tag: v0.5.2
  pullPolicy: IfNotPresent

containerPort: 25

startupProbe:
  enabled: true
  tcpSocket:
    port: 25
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1

livenessProbe:
  enabled: true
  tcpSocket:
    port: 25
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  enabled: true
  tcpSocket:
    port: 25
  initialDelaySeconds: 0
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

command: []
args: []

resources:
  limits: {}
  #   cpu: 200m
  #   memory: 256Mi
  requests: {}
  #   cpu: 100m
  #   memory: 1500Mi

containerSecurityContext:
  enabled: false
  runAsUser: odk
  runAsNonRoot: true

podSecurityContext:
  enabled: false
  fsGroup: 1001

envVars:
  MAILNAME: '{{ .Values.global.mailname }}'
  RELAY_NETWORKS: ':10.0.0.0/8'

envVarsFrom: {}

eximSecret:
  name: ""
  mountPath: "/etc/exim4/"
  mountFiles: []
  # - "_docker_additional_macros"
  # - "domain.key"