apiVersion: v2
name: idgenerator
description: A Helm chart for MOSIP Idgenerator module
type: application
version: 12.0.5
appVersion: "12.0.1"
dependencies:
- name: common
  repository: https://openg2p.github.io/openg2p-helm
  version: 2.30.0
- name: postgres-init
  version: 0.0.0-develop
  repository: https://openg2p.github.io/openg2p-helm
  condition: postgres-init.enabled
keywords:
  - mosip
  - idgenerator
  - kernel
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "Idgenerator"
