## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass
global:
  keycloakBaseUrl: 'https://keycloak.your.org'
  postgresqlHost: commons-postgresql
  kernelDB: mosip_kernel
  kernelDBUser: kerneluser
  kernelDBSecret: kernel
  kernelDBUserPasswordKey: kernel_db_user

hostname: idgenerator.openg2p.sandbox.net

## Add labels to all the deployed resources
##
commonLabels:
  app.kubernetes.io/group: mosip

## Add annotations to all the deployed resources
##
commonAnnotations: {}

## Extra objects to deploy (value evaluated as a template)
##
extraDeploy: []

## Number of nodes
##
replicaCount: 1

service:
  type: ClusterIP
  port: 80
  ## loadBalancerIP for the SuiteCRM Service (optional, cloud specific)
  ## ref: http://kubernetes.io/docs/user-guide/services/#type-loadbalancer
  ##
  ## loadBalancerIP:
  ##
  ## nodePorts:
  ##   http: <to set explicitly, choose port between 30000-32767>
  ##   https: <to set explicitly, choose port between 30000-32767>
  ##

  nodePorts:
    http: ""
    https: ""
  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster

image:
  repository: mosipid/kernel-idgenerator-service
  tag: 1.2.0.1
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## Port on which this particular spring service module is running.
springServicePort: 8080

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
##
startupProbe:
  # Temporarily disabling probe because of long startup times.
  enabled: false
  httpGet:
    path: /v1/idgenerator/actuator/health
    port: 8080
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1

livenessProbe:
  # Temporarily disabling probe because of long startup times.
  enabled: false
  httpGet:
    path: /v1/idgenerator/actuator/health
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /v1/idgenerator/actuator/health
    port: 8080
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## Command and args for running the container (set to default if not set). Use array form
##
command: []
args: []

## Deployment pod host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []

## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
## We usually recommend not to specify default resources and to leave this as a conscious
## choice for the user. This also increases chances charts run on environments with little
## resources, such as Minikube. If you do want to specify resources, uncomment the following
## lines, adjust them as necessary.
# resources:
#   limits:
#     cpu: 1000m
#     memory: 500Mi
#   requests:
#     cpu: 200m
#     memory: 200Mi
resources: {}

## Specify any JAVA_OPTS string here. These typically will be specified in conjunction with above resources. Example:
# javaOpts: "-Xms500M -Xmx500M"
javaOpts: ""

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
## Clamav container already runs as 'mosip' user, so we may not need to enable this
containerSecurityContext:
  enabled: false
  runAsUser: 1001
  runAsNonRoot: true

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext:
  enabled: false
  fsGroup: 1001

## Pod affinity preset
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAffinityPreset: ""

## Pod anti-affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAntiAffinityPreset: soft

## Node affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
## Allowed values: soft, hard
##
nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  ##
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []

## Affinity for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Node labels for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Pod extra labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## Annotations for server pods.
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

##  pods' priority.
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
# priorityClassName: ""

## lifecycleHooks for the  container to automate configuration before or after startup.
##
lifecycleHooks: {}

## Custom Liveness probes for
##
customLivenessProbe: {}

## Custom Rediness probes
##
customReadinessProbe: {}

## Update strategy - only really applicable for deployments with RWO PVs attached
## If replicas = 1, an update can get "stuck", as the previous pod remains attached to the
## PV, and the "incoming" pod can never start. Changing the strategy to "Recreate" will
## terminate the single previous pod, so that the new, incoming pod can attach to the PV
##
updateStrategy:
  type: RollingUpdate

## Add init containers to the  pods.
## Example:
## initContainers:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
initContainers: []

## Add sidecars to the  pods.
## Example:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: []

persistence:
  enabled: false
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack).
  ##
  # storageClass: "-"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # existingClaim: your-claim
  ## ReadWriteMany not supported by AWS gp2
  storageClass:
  accessModes:
    - ReadWriteOnce
  size: 10M
  existingClaim:
  # Dir where config and keys are written inside container
  mountDir:

## Init containers parameters:
## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
##
volumePermissions:
  enabled: false
  image:
    repository: bitnami/bitnami-shell
    tag: "10"
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    pullSecrets: []
    ##   - myRegistryKeySecretName
  ## Init containers' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    ##
    limits: {}
    ##   cpu: 100m
    ##   memory: 128Mi
    ##
    requests: {}
    ##   cpu: 100m
    ##   memory: 128Mi
    ##

## Specifies whether a ServiceAccount should be created
##
serviceAccount:
  create: true
  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the fullname template
  ##
  name:

## Prometheus Metrics
##
metrics:
  enabled: true
  ## Prometheus pod annotations
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations:
    prometheus.io/scrape: "true"

  endpointPath: /v1/idgenerator/actuator/prometheus

  ## Prometheus Service Monitor
  ## ref: https://github.com/coreos/prometheus-operator
  ##
  serviceMonitor:
    ## If the operator is installed in your cluster, set to true to create a Service Monitor Entry
    ##
    enabled: true
    ## Specify the namespace in which the serviceMonitor resource will be created
    ##
    # namespace: ""
    ## Specify the interval at which metrics should be scraped
    ##
    interval: 10s
    ## Specify the timeout after which the scrape is ended
    ##
    # scrapeTimeout: 30s
    ## Specify Metric Relabellings to add to the scrape endpoint
    ##
    # relabellings:
    ## Specify honorLabels parameter to add the scrape endpoint
    ##
    honorLabels: false
    ## Used to pass Labels that are used by the Prometheus installed in your cluster to select Service Monitors to work with
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
    ##
    additionalLabels: {}

  ## Custom PrometheusRule to be defined
  ## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
  ## ref: https://github.com/coreos/prometheus-operator#customresourcedefinitions
  ##
  prometheusRule:
    enabled: false
    additionalLabels: {}
    namespace: ''
    ## List of rules, used as template by Helm.
    ## These are just examples rules inspired from https://awesome-prometheus-alerts.grep.to/rules.html
    # rules:
    #   - alert: RabbitmqDown
    #     expr: rabbitmq_up{service="{{ template "rabbitmq.fullname" . }}"} == 0
    #     for: 5m
    #     labels:
    #       severity: error
    rules: []

## Extra volumes to add to the deployment
##
extraVolumes: []

## Extra volume mounts to add to the container
##
extraVolumeMounts: []

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "internal"
    destination: '{{ template "common.names.fullname" . }}'
    destinationPort: '{{ .Values.service.port }}'
    prefix: /v1/idgenerator
    rewriteUri: ""
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: false
    httpEnabled: true
    httpsEnabled: false
    tls:
      mode: SIMPLE
      credentialName: ""

postgres-init:
  enabled: true
  postgresql:
    host: '{{ .Values.global.postgresqlHost }}'
    port: 5432
    # Hard coding. Same as one defined under Odoo
    existingSecret: commons-postgresql
    existingSecretPostgresPasswordKey: postgres-password
  databases:
    # Same as db in Odoo
    - name: '{{ tpl .Values.global.kernelDB $ }}'
      user: '{{ tpl .Values.global.kernelDBUser $ }}'
      secret: '{{ tpl .Values.global.kernelDBSecret $ }}'
      secretUserPasswordKey: '{{ tpl .Values.global.kernelDBUserPasswordKey $ }}'

## Edit the following properties with names of installation of the dependencies.
artifactoryInstallationName: '{{ .Release.Name }}-artifactory'
postgresqlInstallationName: '{{ .Release.Name }}-postgresql'

coreEnvVars:
  # Env Vars from this section will always be rendered on the service
  JDK_JAVA_OPTIONS: '{{ tpl .Values.javaOpts $ }}'
  spring_cloud_config_enabled_env: '{{ .Values.springCloudConfig.enabled }}'

coreEnvVarsFrom:
  # Env Vars from this section will always be rendered on the service
  artifactory_url_env:
    configMapKeyRef:
      name: '{{ tpl .Values.artifactoryInstallationName $ }}-share'
      key: artifactory_url_env
  iam_adapter_url_env:
    configMapKeyRef:
      name: '{{ tpl .Values.artifactoryInstallationName $ }}-share'
      key: iam_adapter_url_env
  zip_file_path:
    configMapKeyRef:
      name: '{{ tpl .Values.artifactoryInstallationName $ }}-share'
      key: zip_file_path

envVars:
  # Env Vars from this section will be rendered on the service if springCloudConfig.enabled=false.
  # Else they will be rendered on config-server as overrides.
  mosip_api_internal_host: '{{ tpl .Values.hostname $ }}'

  keycloak_internal_url: '{{ tpl .Values.global.keycloakBaseUrl $ }}'
  keycloak_external_url: '{{ tpl .Values.global.keycloakBaseUrl $ }}'

  auth_server_admin_allowed_audience: 'openg2p-sr,openg2p-sr-{{ .Release.Namespace }},openg2p-pbms,openg2p-pbms-{{ .Release.Namespace }},openg2p-spar-{{ .Release.Namespace }}'
  mosip_admin_client_secret: ''

  mosip_kernel_database_hostname: '{{ tpl .Values.postgresqlInstallationName $ }}'

envVarsFrom:
  # Env Vars from this section will be rendered on the service if springCloudConfig.enabled=false.
  # Else they will be rendered on config-server as overrides.
  db_dbuser_password:
    secretKeyRef:
      name: kernel
      key: kernel_db_user

springCloudConfigEnvVars:
  # Env Vars in this section will be rendered on the service, when springCloudConfig.enabled=true.
  spring_cloud_config_label_env:
    secretKeyRef:
      name: '{{ template "common.names.fullname" . }}-config-server-git-secret'
      key: branch
  spring_cloud_config_uri_env: 'http://{{ template "common.names.fullname" . }}-config-server/config'
  spring_profiles_active_env: '{{ tpl .Values.springCloudConfig.profile $ }}'

springCloudConfig:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    nodePorts:
      http: ""
      https: ""
    externalTrafficPolicy: Cluster
  image:
    repository: mosipid/config-server
    tag: 1.1.2
    pullPolicy: Always
    pullSecrets: []
  containerPort: 51000
  startupProbe:
    enabled: true
    httpGet:
      path: /config/*/{{ tpl .Values.springCloudConfig.profile $ }}/{{ tpl .Values.springCloudConfig.gitRepo.branch $ }}
      port: http
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 60
    successThreshold: 1
  livenessProbe:
    enabled: true
    httpGet:
      path: /config/*/{{ tpl .Values.springCloudConfig.profile $ }}/{{ tpl .Values.springCloudConfig.gitRepo.branch $ }}
      port: http
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    httpGet:
      path: /config/*/{{ tpl .Values.springCloudConfig.profile $ }}/{{ tpl .Values.springCloudConfig.gitRepo.branch $ }}
      port: http
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  command: []
  args: []
  hostAliases: []
  resources: {}
  containerSecurityContext:
    enabled: false
    runAsUser: 1001
    runAsNonRoot: true
  podSecurityContext:
    enabled: false
    fsGroup: 1001
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  podLabels:
    app.kubernetes.io/name: '{{ include "common.names.name" . }}-config-server'
  podAnnotations: {}
  # priorityClassName: ""
  lifecycleHooks: {}
  updateStrategy:
    type: RollingUpdate
  initContainers: []
  sidecars: []
  volumePermissions:
    enabled: false
    image:
      repository: bitnami/bitnami-shell
      tag: "10"
      pullPolicy: Always
      pullSecrets: []
      ##   - myRegistryKeySecretName
    resources: {}
  extraVolumes: []
  extraVolumeMounts: []

  profile: default
  gitRepo:
    url: https://github.com/openg2p/mosip-config
    branch: master
  envVars:
    # Env Vars in these sections will be rendered on config server.
    SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS: ""
  envVarsFrom:
    # Env Vars in these sections will be rendered on config server.
    SPRING_CLOUD_CONFIG_SERVER_GIT_URI:
      secretKeyRef:
        name: '{{ template "common.names.fullname" . }}-config-server-git-secret'
        key: url

startUpCommand: |-
  #!/usr/bin/env bash

  echo "Waiting for artifactory..."
  if ! curl -I -s -o /dev/null -m 10 --retry 100 --retry-delay 10 --retry-all-errors "${iam_adapter_url_env}"; then
    echo "Connecting with artifactory failed after max retries..."
    exit 1
  fi

  # TODO: Wait for postgres
  sleep 10s

  ADDL_ARGS=()

  wget "${artifactory_url_env}"/artifactory/libs-release-local/io/mosip/testing/regproc-reprocessor-ceylon-cache-repo.zip
  unzip regproc-reprocessor-ceylon-cache-repo.zip
  rm -rf regproc-reprocessor-ceylon-cache-repo.zip
  ADDL_ARGS+=("-Dceylon.cache.repo=./regproc-reprocessor-ceylon-cache-repo")

  wget -q "${iam_adapter_url_env}" -O "${loader_path_env}"/kernel-auth-adapter.jar

  if [ "$is_glowroot_env" = "present" ]; then
    wget -q "${artifactory_url_env}"/artifactory/libs-release-local/io/mosip/testing/glowroot.zip
    unzip glowroot.zip
    rm -rf glowroot.zip
    sed -i 's/<service_name>/kernel-idgenerator-service/g' glowroot/glowroot.properties
    ADDL_ARGS+=("-javaagent:glowroot/glowroot.jar -XX:HeapDumpPath=/home/")
  fi

  if [ "$spring_cloud_config_enabled_env" = "true" ]; then
    echo "Waiting for config server..."
    if ! curl -I -s -o /dev/null -m 10 --retry 100 --retry-delay 10 --retry-all-errors "${spring_cloud_config_uri_env}/*/*"; then
      echo "Connecting with artifactory failed after max retries..."
      exit 1
    fi
    ADDL_ARGS+=("-Dspring.cloud.config.label=${spring_cloud_config_label_env}")
    ADDL_ARGS+=("-Dspring.cloud.config.uri=${spring_cloud_config_uri_env}")
    ADDL_ARGS+=("-Dspring.profiles.active=${spring_profiles_active_env}")
    ADDL_ARGS+=("-Dspring.cloud.config.enabled=true")
    ADDL_ARGS+=("-Dspring.cloud.bootstrap.enabled=true")
  else
    if [ -f springConfig/application.properties ]; then
      config_locations="classpath:/bootstrap.properties,springConfig/application.properties"
      ADDL_ARGS+=("-Dspring.config.location=${config_locations}")
    fi
    ADDL_ARGS+=("-Dspring.cloud.config.enabled=false")
    ADDL_ARGS+=("-Dspring.cloud.bootstrap.enabled=false")
  fi

  ADDL_ARGS+=("-Dloader.path=${loader_path_env}")

  exec java -jar ${ADDL_ARGS[@]} ./kernel-idgenerator-service.jar
