apiVersion: v2
name: artifactory
description: A Helm chart for MOSIP Artifactory
type: application
version: 12.0.3
appVersion: ""
dependencies:
  - name: common
    repository: https://openg2p.github.io/openg2p-helm
    version: 2.30.0
home: https://mosip.io
keywords:
  - artifactory
  - antivirus
  - anti-virus
maintainers:
  - email: info@mosip.io
    name: MOSIP
