apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-client-initializer.fullname" . }}-keycloak-templates
  labels:
    {{- include "keycloak-client-initializer.labels" . | nindent 4 }}
data:
  config.template.json: |
  {{ .Values.keycloakTemplates.configTemplateJson | nindent 4 }}
client.template.json: |
  {{ .Values.keycloakTemplates.clientTemplateJson | nindent 4 }}
