{{- if .Values.createAdminPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.adminPasswordSecretName }}
  labels:
    {{- include "keycloak-client-initializer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.keycloak.adminPasswordSecretKey }}: {{ .Values.keycloakAdminPassword | quote }}
  {{- end }}
