apiVersion: v2
name: mimoto
description: A Helm chart for Mimoto (Inji Backend)
type: application
version: 0.13.2
dependencies:
- name: common
  repository: https://openg2p.github.io/openg2p-helm
  version: 2.30.0
- name: artifactory
  repository: https://openg2p.github.io/openg2p-helm
  version: 12.0.2
  condition: artifactory.enabled
keywords:
  - mosip
  - mimoto
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "Mimoto"
