{{- if .Values.istio.enabled  }}
{{- if .Values.istio.gateway.enabled  }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{ toYaml .Values.istio.gateway.ingressController | nindent 4 }}
  servers:
  {{- if .Values.istio.gateway.httpEnabled }}
  - port:
      name: http2
      number: 8080
      protocol: HTTP2
    hosts:
      - {{ default .Values.hostname .Values.istio.gateway.host | quote }}
    {{- if .Values.istio.gateway.httpTlsRedirect }}
    tls:
      httpsRedirect: true
    {{- end }}
  {{- end }}
  {{- if .Values.istio.gateway.httpsEnabled }}
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
      - {{ default .Values.hostname .Values.istio.gateway.host | quote }}
    tls:
      {{ toYaml (omit .Values.istio.gateway.tls "enabled") | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
