apiVersion: v2
name: odk-central
description: A Helm chart for odk-central.
type: application
version: v2025.2.2
dependencies:
- name: common
  repository: https://openg2p.github.io/openg2p-helm
  version: 2.30.0
- name: odk-central-pyxform
  version: v2025.2.2
  condition: odk-central-pyxform.enabled
- name: odk-central-enketo
  version: v2025.2.2
  condition: odk-central-enketo.enabled
keywords:
  - odk
  - odk-central
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "ODK Central"
