apiVersion: v2
name: odk-central
description: A Helm chart for odk-central.
type: application
version: "v2024.1.0"
dependencies: 
  - name: mail
    alias: odk-central-mail
    version: "1.2.0"
    condition: odk-central-mail.enabled
  - name: odk-central-pyxform
    version: "v2024.1.0"
    condition: odk-central-pyxform.enabled
  - name: odk-central-enketo
    version: "v2024.1.0"
    condition: odk-central-enketo.enabled
  - name: odk-central-backend
    version: "v2024.1.0"
    condition: odk-central-backend.enabled
  - name: odk-central-frontend
    version: "v2024.1.0"
    condition: odk-central-frontend.enabled
keywords:
  - odk
  - odk-central
maintainers:
  - email: lalith@openg2p.org
    name: lalithkota
annotations:
  catalog.cattle.io/display-name: "ODK Central"
